version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql

  web:
    build: ./docker/web
    image: myapp:latest
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://root:password@db/myapp_development
    volumes:
      - ./src:/app
      - ./src/node_modules:/app/node_modules

volumes:
  db:
  node_modules: